[package]
name = "trip"
version = "0.1.0"
authors = ["Will Alexander <wwalexander@users.noreply.github.com>"]
description = "Finds tripcodes that contain patterns."
license = "MIT/Apache-2.0"

[dependencies]
rand = "0.3.15"